title = "Crack zip file password"
description = "Extract the hash of a zip file and crack it based on a wordlist"
tags = ["cracking", "zip", "crypto"]
source = []

[[data]]
description = ""
language = "bash"
command = """zip2john file.zip > hash.txt
john hash.txt
john hash.txt --show"""
