title = "Permanently delete a file"
description = "Overwrites a file's data 40 times with random patterns and delete it"
tags = ["misc"]
source = []

[[data]]
description = "Substitute <file>:"
language = "bash"
command = """shred -vfzun40 <file>"""