title = "Pull Android mobile app .apk from phone"
description = "Extract the .apk from a mobile app provided the application package id"
tags = ["mobile", "android", "bash", "apk"]
source = []

[[data]]
description = "Usage: pull-apk <package id>:"
language = "bash"
command = """function pull-apk(){
	pkg_name=$(adb shell pm list packages | cut -d: -f2 | grep $1)
	adb pull "$(adb shell pm path $pkg_name | cut -d: -f2 | grep base)"
	mv base.apk $pkg_name.apk &> /dev/null
}"""
